### ISSUE TITLE
Is there any character limitation on Extra Entries property?

### ISSUE THREAD

**Issue by mathiasmaciel97** [Pretius/Pretius-APEX-Context-Menu#5]
At some point when I try to add more logic on Extra Entries I get error message: value is too long

![Screenshot_1](https://user-images.githubusercontent.com/39440207/98727206-5ab73000-2376-11eb-8057-f4d30b789bf0.png)

![Screenshot_2](https://user-images.githubusercontent.com/39440207/98727215-5db22080-2376-11eb-9d33-813cbfd96918.png)

Thanks in advance
Mathias

**Comment by bostrowski** [comment]
@mathiasmaciel97 
This is apex limitation for all attributes within Page Designer. 

to make it work:

1. wrap your code as a function declared in (for example) Page \ JavaScript \ Function and Global Variable Declaration
2. put your function in the plug-in attribute

```js
return yourFunctionReturningArray();
```

**Comment by mathiasmaciel97** [comment]
Could you provide an example creating a function and declaring it at Function and Global Variable Declaration? I'm a little bit bad with JS

**Comment by bostrowski** [comment]
sure

![image](https://user-images.githubusercontent.com/15342508/98730017-feff9d80-239b-11eb-9333-d314962a111e.png)

variable ```arrayToReturn``` should contain an array you were unable to save because of exceeding the max character limitation for apex attributes.

I hope it's enough explanation ;-)

Ps.
The page attribute ```Function And Global Variable Definition``` has limitation too. The best approach is to create a separate JavaScript File, add it to ```Static Application Files``` and attach through ```User InterfacesUser Interface Details \ JavaScript \ File URLs```

**Comment by mathiasmaciel97** [comment]
Works! Thanks for all your explanation, your time and your patience to guide through this. I appreciate your compromise to help others for free!
